name: Test Project

on:
    pull_request:
        branches:
            - main
# adding a minore change to test the workflows123addasd
jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: node:20
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm ci
            - run: npm test
            - run: npm run build